#include <time.h>
#include "ABB.h"
#include "AVL.h"

FILE* open_file(char* path, char* mode);

int main () {
	FILE* data = open_file("data.txt", "w");
    clock_t t;
    t = clock();
	binary_tree* AVL = create_empty_tree();
	binary_tree* ABB = create_empty_tree();
	int num, i, j;
	printf("Numero de items a serem inseridos: ");
	int items;
	scanf("%d", &items);
	// Number of items that will be added on the trees.
	printf("Digite o numero de buscas: ");
	int searchs;
	scanf("%d", &searchs);
	// Number of tests (searchs) that will be done with random numbers (can repeat).
	srand(time(NULL));
    int n;
	for(i = 0; i < items; i++) {
        // n = rand() % items;
		AVL = add_avl(AVL, i);
		ABB = add_abb(ABB, i);
	}
	int compareABB = 0;
	int compareAVL = 0;

	for(i = 0; i < searchs; i++){
		
		int num = ((rand() << 8) | rand()) % items;
		if(num < 0){
			num = num * (-1);
		}
		// printf("Sorted: %d\n", num);
		// Shiftbit to increase the size of the random number generated by function rand().
		// search_abb(ABB_sorted, num, &compareABB_sorted);
		search_abb(ABB, num, &compareABB);
		search_avl(AVL, num, &compareAVL);
		// Do the search on all the 3 trees get how many comparisons was done in each one.

		fprintf(data, "%d;%d;%d\n", num, compareABB, compareAVL);
		compareABB = 0;
		compareAVL = 0;
	}

	fclose(data);
	t = clock() - t;
	double time_taken = ((double)t)/CLOCKS_PER_SEC;
	printf("Took %.2f seconds to execute \n", time_taken);
	// print_pre_order(ABB);
	// Time counter.

	return 0;
}

FILE* open_file(char* path, char* mode) {

    FILE *f = fopen(path, mode);

    if (f == NULL) {
        printf("Error opening file %s.\n", path);
        exit(1);
    }

    return f;
}

